#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "ir_protocol.h"
#include "ir_rx.h"
#include "ir_tx.h"
#include "ir_transport_uart.h"
#include "sdkconfig.h"

static ir_code_t last;
static ir_code_t sent;
static esp_err_t rx_result = ESP_ERR_TIMEOUT;
static unsigned captures;
static esp_err_t tx_result = ESP_OK;
static unsigned transmissions;
static uint8_t reply[IR_PROTOCOL_MAX_PACKET];
static size_t reply_len;
static unsigned replies;

esp_err_t ir_rx_capture(ir_code_t *code, uint32_t timeout_ms)
{
    assert(timeout_ms == CONFIG_IR_RX_CAPTURE_TIMEOUT_MS);
    ++captures;
    if (rx_result == ESP_OK) { *code = last; }
    return rx_result;
}
esp_err_t ir_tx_send(const ir_code_t *code)
{
    assert(ir_code_is_valid(code));
    sent = *code;
    ++transmissions;
    return tx_result;
}
esp_err_t ir_transport_write(const uint8_t *bytes, size_t len)
{
    assert(len >= 16 && len <= sizeof(reply));
    assert(ir_read_u32_le(bytes + 8) == len - 16);
    assert(ir_protocol_crc32(bytes, bytes + 16, len - 16) == ir_read_u32_le(bytes + 12));
    memcpy(reply, bytes, len);
    reply_len = len;
    ++replies;
    return ESP_OK;
}
int ir_transport_read(uint8_t *bytes, size_t len, TickType_t timeout)
{
    (void)bytes; (void)len; (void)timeout; return 0;
}
int64_t esp_timer_get_time(void) { return 0; }
int xTaskCreate(void (*task)(void *), const char *name, unsigned stack,
                void *arg, unsigned priority, void *handle)
{
    (void)task; (void)name; (void)stack; (void)arg; (void)priority; (void)handle;
    return pdPASS;
}

static void checksum(uint8_t *packet, size_t len)
{
    ir_write_u32_le(packet + 12, ir_protocol_crc32(packet, packet + 16, len - 16));
}
static size_t packet(uint8_t *out, uint8_t command, const uint8_t *payload, size_t len)
{
    memset(out, 0, 16);
    out[0] = 'I'; out[1] = 'R'; out[2] = 1; out[3] = command;
    ir_write_u16_le(out + 6, 0x1234);
    ir_write_u32_le(out + 8, (uint32_t)len);
    if (len) { memcpy(out + 16, payload, len); }
    checksum(out, 16 + len);
    return 16 + len;
}
static void expect(const uint8_t *bytes, size_t len, uint8_t status)
{
    ir_protocol_reset();
    unsigned before = replies;
    ir_protocol_feed(bytes, len);
    assert(replies == before + 1);
    assert(reply[3] == bytes[3] && reply[4] == 1 && reply[5] == status);
    assert(ir_read_u16_le(reply + 6) == 0x1234);
}

int main(void)
{
    uint8_t request[IR_PROTOCOL_MAX_PACKET];
    uint8_t payload[IR_PROTOCOL_MAX_PAYLOAD];
    uint8_t ping[16];
    size_t payload_len;
    last = (ir_code_t){
        .symbol_count = 1, .resolution_hz = IR_RESOLUTION_HZ,
        .symbols = {{{.duration = 3320, .level = 1}, {.duration = 9936, .level = 0}}},
    };
    assert(ir_protocol_encode_code(&last, payload, sizeof(payload), &payload_len) == ESP_OK);
    assert(payload_len == 16);
    assert(memcmp(payload + 12, "\xF8\x8C\xD0\x26", 4) == 0);
    assert(ir_protocol_encode_code(&last, payload, 15, &payload_len) == ESP_ERR_INVALID_SIZE);
    packet(ping, IR_COMMAND_PING, NULL, 0);
    expect(ping, 16, IR_STATUS_OK);
    /* Independent zlib vector, not generated by the implementation under test. */
    const uint8_t known_read[] = {0x49,0x52,1,1,0,0,1,0,0,0,0,0,0x33,0x83,0x28,0xc5};
    assert(ir_protocol_crc32(known_read, NULL, 0) == 0xC5288333U);
    const uint8_t known_write[] = {
        0x49,0x52,1,2,0,0,2,0,0x10,0,0,0,0x7d,0xb0,0xdb,0x60,
        1,0,0,0,0x40,0x42,0x0f,0,0,0,0,0,0xf8,0x8c,0xd0,0x26
    };
    assert(ir_protocol_crc32(known_write, known_write + 16, 16) == 0x60DBB07DU);
    size_t len = packet(request, IR_COMMAND_READ, NULL, 0);
    expect(request, len, IR_STATUS_NO_DATA);
    assert(captures == 1 && reply_len == 16);
    rx_result = ESP_OK;
    expect(request, len, IR_STATUS_OK);
    assert(reply_len == 32 && memcmp(reply + 16, payload, 16) == 0);
    expect(request, len, IR_STATUS_OK);
    assert(captures == 3);
    /* A READ after success must start a new capture, never replay stale data. */
    rx_result = ESP_ERR_TIMEOUT;
    expect(request, len, IR_STATUS_NO_DATA);
    assert(captures == 4 && reply_len == 16);
    rx_result = ESP_ERR_NOT_FINISHED;
    expect(request, len, IR_STATUS_BUSY);
    rx_result = ESP_FAIL;
    expect(request, len, IR_STATUS_INTERNAL_ERROR);
    rx_result = ESP_OK;
    len = packet(request, IR_COMMAND_WRITE, payload, payload_len);
    expect(request, len, IR_STATUS_OK);
    assert(sent.symbols[0].phase0.duration == 3320 && sent.carrier_hz == 0);
    tx_result = ESP_ERR_TIMEOUT;
    expect(request, len, IR_STATUS_BUSY);
    tx_result = ESP_FAIL;
    expect(request, len, IR_STATUS_TX_ERROR);
    tx_result = ESP_OK;
    unsigned before_rx = captures;
    unsigned before_tx = transmissions;
    request[31] ^= 1;
    expect(request, len, IR_STATUS_CRC_ERROR);
    assert(transmissions == before_tx);
    request[31] ^= 1;
    /* Every split point, including one byte at a time. */
    for (size_t split = 0; split <= len; ++split) {
        ir_protocol_reset();
        unsigned before = replies;
        ir_protocol_feed(request, split);
        ir_protocol_feed(request + split, len - split);
        assert(replies == before + 1 && reply[5] == IR_STATUS_OK);
    }
    ir_protocol_reset();
    for (size_t i = 0; i < len; ++i) { ir_protocol_feed(request + i, 1); }
    assert(reply[5] == IR_STATUS_OK);
    /* Noise, overlapping magic and concatenated packets. */
    ir_protocol_reset();
    ir_protocol_feed((const uint8_t *)"xyzIII", 6);
    unsigned before = replies;
    ir_protocol_feed(ping, sizeof(ping));
    ir_protocol_feed(ping, sizeof(ping));
    assert(replies == before + 2);
    /* Recover after over-limit length without copying its payload. */
    memcpy(request, ping, 16);
    ir_write_u32_le(request + 8, UINT32_MAX);
    expect(request, 16, IR_STATUS_INVALID_LENGTH);
    ir_protocol_feed(ping, sizeof(ping));
    assert(reply[5] == IR_STATUS_OK);
    /* A plausible damaged length cannot hold subsequent traffic indefinitely. */
    memcpy(request, ping, 16);
    ir_write_u32_le(request + 8, 1000);
    ir_protocol_reset();
    ir_protocol_feed(request, 16);
    ir_protocol_feed(ping, 16);
    before = replies;
    ir_protocol_expire();
    assert(replies == before + 1 && reply[5] == IR_STATUS_OK);
    /* CRC recovery rescans bytes, including magic inside a corrupt candidate. */
    memcpy(request, ping, 16);
    ir_write_u32_le(request + 8, 16);
    memcpy(request + 16, ping, 16);
    ir_protocol_reset();
    before = replies;
    ir_protocol_feed(request, 32);
    assert(replies == before + 2 && reply[5] == IR_STATUS_OK);
    /* All semantic failures must leave the transmitter untouched. */
    before_tx = transmissions;
    len = packet(request, 0x99, NULL, 0);
    expect(request, len, IR_STATUS_INVALID_COMMAND);
    len = packet(request, IR_COMMAND_READ, payload, 16);
    expect(request, len, IR_STATUS_INVALID_LENGTH);
    len = packet(request, IR_COMMAND_PING, payload, 16);
    expect(request, len, IR_STATUS_INVALID_LENGTH);
    len = packet(request, IR_COMMAND_WRITE, NULL, 0);
    expect(request, len, IR_STATUS_INVALID_LENGTH);
    const unsigned bad_offsets[] = {16, 18, 20, 24, 28, 29, 31};
    for (size_t i = 0; i < sizeof(bad_offsets) / sizeof(bad_offsets[0]); ++i) {
        len = packet(request, IR_COMMAND_WRITE, payload, 16);
        unsigned offset = bad_offsets[i];
        if (offset == 16) { request[offset] = 0; }
        else if (offset == 28) { request[28] = 0; request[29] = 0x80; }
        else if (offset == 29 || offset == 31) { request[offset] ^= 0x80; }
        else { request[offset] ^= 1; }
        checksum(request, len);
        expect(request, len, IR_STATUS_INVALID_PAYLOAD);
    }
    len = packet(request, IR_COMMAND_WRITE, payload, 15);
    expect(request, len, IR_STATUS_INVALID_LENGTH);
    for (unsigned offset = 2; offset <= 5; ++offset) {
        if (offset == 3) { continue; }
        len = packet(request, IR_COMMAND_WRITE, payload, 16);
        request[offset] = 2;
        checksum(request, len);
        expect(request, len, IR_STATUS_INVALID_PAYLOAD);
    }
    assert(transmissions == before_tx);
    assert(captures == before_rx);
    /* Invalid READ packets and incoming responses must not enable capture. */
    len = packet(request, IR_COMMAND_READ, NULL, 0);
    request[12] ^= 1;
    expect(request, len, IR_STATUS_CRC_ERROR);
    request[12] ^= 1;
    request[2] = 2;
    checksum(request, len);
    expect(request, len, IR_STATUS_INVALID_PAYLOAD);
    assert(captures == before_rx);
    memcpy(request, ping, 16); request[4] = 1; checksum(request, 16);
    ir_protocol_reset(); before = replies;
    ir_protocol_feed(request, 16); assert(replies == before);
    /* Maximum count/duration and terminal zero SPACE round-trip. */
    last.symbol_count = IR_MAX_SYMBOLS;
    last.carrier_hz = IR_MAX_CARRIER_HZ;
    for (unsigned i = 0; i < IR_MAX_SYMBOLS; ++i) {
        last.symbols[i] = (ir_symbol_t){{32767, 1}, {32767, 0}};
    }
    last.symbols[IR_MAX_SYMBOLS - 1].phase1.duration = 0;
    assert(ir_protocol_encode_code(&last, payload, sizeof(payload), &payload_len) == ESP_OK);
    assert(payload_len == IR_PROTOCOL_MAX_PAYLOAD);
    len = packet(request, IR_COMMAND_WRITE, payload, payload_len);
    expect(request, len, IR_STATUS_OK);
    assert(sent.symbol_count == 256 && sent.symbols[255].phase1.duration == 0);
    last.symbols[0].phase1.duration = 0;
    assert(!ir_code_is_valid(&last));
    ir_write_u16_le(payload, 257);
    len = packet(request, IR_COMMAND_WRITE, payload, payload_len);
    expect(request, len, IR_STATUS_INVALID_PAYLOAD);
    /* Deterministic noise under ASan/UBSan, followed by a valid frame. */
    uint32_t random = 1234567;
    ir_protocol_reset();
    for (unsigned i = 0; i < 100000; ++i) {
        random = random * 1664525U + 1013904223U;
        uint8_t byte = (uint8_t)(random >> 24);
        ir_protocol_feed(&byte, 1);
    }
    ir_protocol_expire();
    ir_protocol_feed(ping, 16);
    assert(reply[5] == IR_STATUS_OK);
    puts("Protocol tests passed (framing, CRC, validation, limits, recovery, READ/WRITE).");
    return 0;
}
